version: '3'
services:
  app:
    build: .
    volumes:
      - .:/opt/app
    stdin_open: true
    tty: true
    environment:
      REDIS_HOST: db
    depends_on:
      - db
  db:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"